# Generated by Django 4.2.2 on 2023-06-26 21:18

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Usuario",
            fields=[
                ("cpf", models.BigIntegerField(primary_key=True, serialize=False)),
                ("nome", models.CharField(max_length=80)),
                ("data_nascimento", models.DateField()),
            ],
        ),
    ]
