# Generated by Django 4.2.2 on 2023-07-13 03:41

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Usuario",
            fields=[
                ("cpf", models.IntegerField(primary_key=True, serialize=False)),
                ("nome", models.TextField()),
                ("data_nascimento", models.DateField()),
            ],
        ),
    ]
